### ISSUE TITLE
java.lang.NoClassDefFoundError: Lflavor/pie/boop/metrics/sponge/MetricsLite;

### ISSUE THREAD

**Issue by sfxworks** [pie-flavor/Boop#7]
Minecraft version: 1.12.2
Forge version: 14.23.4.2705
Singleplayer or multiplayer: Multiplayer
Steps to reproduce: On launch / Server start
When starting server for using Boop 1.6.0, I get the following crash report:

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.181.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-82-core.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.31.jar)
  LoadingPlugin (Quark-r1.4-125.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  SpongeCoremod (spongeforge-1.12.2-2705-7.1.0-BETA-3151.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.1.8.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 6/28/18 7:43 AM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Boop (boop)
Caused by: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: Lflavor/pie/boop/metrics/sponge/MetricsLite;
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2215)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153)
	at com.google.inject.internal.FailableCache.get(FailableCache.java:48)
	at com.google.inject.internal.ConstructorInjectorStore.get(ConstructorInjectorStore.java:50)
	at com.google.inject.internal.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:138)
	at com.google.inject.internal.InjectorImpl.initializeBinding(InjectorImpl.java:536)
	at com.google.inject.internal.AbstractBindingProcessor$Processor$1.run(AbstractBindingProcessor.java:160)
	at com.google.inject.internal.ProcessedBindingData.initializeBindings(ProcessedBindingData.java:44)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:123)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:232)
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:236)
	at org.spongepowered.mod.plugin.SpongeModPluginContainer.constructMod(SpongeModPluginContainer.java:282)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:560)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:332)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: Lflavor/pie/boop/metrics/sponge/MetricsLite;
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2215)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153)
	at com.google.inject.internal.FailableCache.get(FailableCache.java:48)
	at com.google.inject.internal.MembersInjectorStore.get(MembersInjectorStore.java:68)
	at com.google.inject.internal.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:75)
	at com.google.inject.internal.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:29)
	at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:37)
	at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:33)
	at com.google.inject.internal.FailableCache$1.load(FailableCache.java:37)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
	... 47 more
Caused by: java.lang.NoClassDefFoundError: Lflavor/pie/boop/metrics/sponge/MetricsLite;
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getDeclaredFields(Class.java:1916)
	at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:675)
	at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:380)
	at com.google.inject.internal.MembersInjectorStore.createWithListeners(MembersInjectorStore.java:93)
	at com.google.inject.internal.MembersInjectorStore.access$000(MembersInjectorStore.java:37)
	at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:45)
	at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:42)
	at com.google.inject.internal.FailableCache$1.load(FailableCache.java:37)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
	... 62 more
Caused by: java.lang.ClassNotFoundException: flavor.pie.boop.metrics.sponge.MetricsLite
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 76 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zjm000(MinecraftServer.java:3997)

-- Sponge PhaseTracker --
Details:
	Phase Stack: [Empty stack]
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zjm000(MinecraftServer.java:3997)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:889)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:370)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:558)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.4.111+
	Java Version: 1.8.0_151, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3612104176 bytes (3444 MB) / 7652507648 bytes (7298 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 15 total; -Xms256M -Xmx8192M -XX:MaxRAM=8192M -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:InitiatingHeapOccupancyPercent=10 -XX:G1MixedGCLiveThresholdPercent=50 -XX:+AggressiveOpts -XX:+AlwaysPreTouch -XX:+UseCGroupMemoryLimitForHeap
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2705 119 mods loaded, 119 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                | Version                      | Source                                             | Signature                                |
	|:----- |:--------------------------------- |:---------------------------- |:-------------------------------------------------- |:---------------------------------------- |
	| UC    | minecraft                         | 1.12.2                       | minecraft.jar                                      | None                                     |
	| UC    | mcp                               | 9.42                         | minecraft.jar                                      | None                                     |
	| UC    | FML                               | 8.0.99.99                    | server.jar                                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | forge                             | 14.23.4.2705                 | server.jar                                         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | micdoodlecore                     |                              | minecraft.jar                                      | None                                     |
	| UC    | spongeapi                         | 7.1.0-SNAPSHOT-43d8496       | spongeforge-1.12.2-2705-7.1.0-BETA-3151.jar        | None                                     |
	| UC    | sponge                            | 1.12.2-2705-7.1.0-BETA-3151  | spongeforge-1.12.2-2705-7.1.0-BETA-3151.jar        | 6729a677746f8cf63ef31881f913ed15d431b7f0 |
	| UC    | openmodscore                      | 0.11.5                       | minecraft.jar                                      | None                                     |
	| UC    | actuallyadditions                 | 1.12.2-r135                  | ActuallyAdditions-1.12.2-r135.jar                  | None                                     |
	| UC    | ic2                               | 2.8.90-ex112                 | industrialcraft-2-2.8.90-ex112.jar                 | de041f9f6187debbc77034a344134053277aa3b0 |
	| UC    | advanced_solar_panels             | 4.2.0                        | Advanced Solar Panels-4.2.0.jar                    | None                                     |
	| UC    | appliedenergistics2               | rv5-stable-11                | appliedenergistics2-rv5-stable-11.jar              | None                                     |
	| UC    | bdlib                             | 1.14.3.12                    | bdlib-1.14.3.12-mc1.12.2.jar                       | None                                     |
	| UC    | ae2stuff                          | 0.7.0.4                      | ae2stuff-0.7.0.4-mc1.12.2.jar                      | None                                     |
	| UC    | ambience                          | GRADLE:VERSION-GRADLE:BUILD  | Ambience 1.1-10.jar                                | None                                     |
	| UC    | quark                             | r1.4-125                     | Quark-r1.4-125.jar                                 | None                                     |
	| UC    | autoreglib                        | 1.3-18                       | AutoRegLib-1.3-18.jar                              | None                                     |
	| UC    | baubles                           | 1.5.2                        | Baubles-1.12-1.5.2.jar                             | None                                     |
	| UC    | codechickenlib                    | 3.2.0.345                    | CodeChickenLib-1.12.2-3.2.0.345-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UC    | redstoneflux                      | 2.0.2                        | RedstoneFlux-1.12-2.0.2.3-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UC    | brandonscore                      | 2.4.3                        | BrandonsCore-1.12.2-2.4.3.168-universal.jar        | None                                     |
	| UC    | buildcraftlib                     | 7.99.17                      | buildcraft-7.99.17.jar                             | None                                     |
	| UC    | buildcraftcore                    | 7.99.17                      | buildcraft-7.99.17.jar                             | None                                     |
	| UC    | buildcraftbuilders                | 7.99.17                      | buildcraft-7.99.17.jar                             | None                                     |
	| UC    | buildcraftenergy                  | 7.99.17                      | buildcraft-7.99.17.jar                             | None                                     |
	| UC    | buildcraftfactory                 | 7.99.17                      | buildcraft-7.99.17.jar                             | None                                     |
	| UC    | buildcraftrobotics                | 7.99.17                      | buildcraft-7.99.17.jar                             | None                                     |
	| UC    | buildcrafttransport               | 7.99.17                      | buildcraft-7.99.17.jar                             | None                                     |
	| UC    | buildcraftsilicon                 | 7.99.17                      | buildcraft-7.99.17.jar                             | None                                     |
	| UC    | buildcraftcompat                  | 7.99.14                      | buildcraft-compat-7.99.14.jar                      | None                                     |
	| UC    | cofhcore                          | 4.5.2                        | CoFHCore-1.12.2-4.5.2.19-universal.jar             | None                                     |
	| UC    | cofhworld                         | 1.2.0                        | CoFHWorld-1.12.2-1.2.0.5-universal.jar             | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UC    | computercraft                     | 1.80pr1                      | ComputerCraft1.80pr1.jar                           | None                                     |
	| UC    | customnpcs                        | 1.12                         | CustomNPCs_1.12.2(13may18).jar                     | None                                     |
	| UC    | thermalfoundation                 | 2.5.0                        | ThermalFoundation-1.12.2-2.5.0.19-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UC    | draconicevolution                 | 2.3.12                       | Draconic-Evolution-1.12.2-2.3.12.297-universal.jar | None                                     |
	| UC    | endercore                         | 1.12.2-0.5.31                | EnderCore-1.12.2-0.5.31.jar                        | None                                     |
	| UC    | jei                               | 4.9.2.196                    | jei_1.12.2-4.9.2.196.jar                           | None                                     |
	| UC    | thermalexpansion                  | 5.5.0                        | ThermalExpansion-1.12.2-5.5.0.29-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UC    | enderio                           | 5.0.26                       | EnderIO-1.12.2-5.0.26.jar                          | None                                     |
	| UC    | enderiointegrationtic             | 5.0.26                       | EnderIO-1.12.2-5.0.26.jar                          | None                                     |
	| UC    | enderiobase                       | 5.0.26                       | EnderIO-1.12.2-5.0.26.jar                          | None                                     |
	| UC    | enderioconduits                   | 5.0.26                       | EnderIO-1.12.2-5.0.26.jar                          | None                                     |
	| UC    | enderioconduitsappliedenergistics | 5.0.26                       | EnderIO-1.12.2-5.0.26.jar                          | None                                     |
	| UC    | enderioconduitsopencomputers      | 5.0.26                       | EnderIO-1.12.2-5.0.26.jar                          | None                                     |
	| UC    | enderioconduitsrefinedstorage     | 5.0.26                       | EnderIO-1.12.2-5.0.26.jar                          | None                                     |
	| UC    | enderiointegrationforestry        | 5.0.26                       | EnderIO-1.12.2-5.0.26.jar                          | None                                     |
	| UC    | mantle                            | 1.12-1.3.2.24                | Mantle-1.12-1.3.2.24.jar                           | None                                     |
	| UC    | tconstruct                        | 1.12.2-2.10.1.87             | TConstruct-1.12.2-2.10.1.87.jar                    | None                                     |
	| UC    | enderiointegrationticlate         | 5.0.26                       | EnderIO-1.12.2-5.0.26.jar                          | None                                     |
	| UC    | enderiomachines                   | 5.0.26                       | EnderIO-1.12.2-5.0.26.jar                          | None                                     |
	| UC    | enderiopowertools                 | 5.0.26                       | EnderIO-1.12.2-5.0.26.jar                          | None                                     |
	| UC    | enderstorage                      | 2.4.4.132                    | EnderStorage-1.12.2-2.4.4.132-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UC    | exnihilocreatio                   | 1.12-0.2.4                   | exnihilocreatio-1.12-0.2.4.jar                     | None                                     |
	| UC    | excompressum                      | 3.0.22                       | ExCompressum_1.12.2-3.0.22.jar                     | None                                     |
	| UC    | extracells                        | 2.5.13                       | ExtraCells-1.12.2-2.5.13a60.jar                    | None                                     |
	| UC    | galacticraftcore                  | 4.0.1.181                    | GalacticraftCore-1.12.2-4.0.1.181.jar              | None                                     |
	| UC    | galacticraftplanets               | 4.0.1.181                    | Galacticraft-Planets-1.12.2-4.0.1.181.jar          | None                                     |
	| UC    | mjrlegendslib                     | 1.12.2-1.1.4                 | MJRLegendsLib-1.12.2-1.1.4.jar                     | b02331787272ec3515ebe63ecdeea0d746653468 |
	| UC    | extraplanets                      | 1.12.2-0.4.0                 | ExtraPlanets-1.12.2-0.4.0.jar                      | b02331787272ec3515ebe63ecdeea0d746653468 |
	| UC    | zerocore                          | 1.12-0.1.2.2                 | zerocore-1.12-0.1.2.2.jar                          | None                                     |
	| UC    | bigreactors                       | 1.12.2-0.4.5.49              | ExtremeReactors-1.12.2-0.4.5.49.jar                | None                                     |
	| UC    | facmod                            | SNAPSHOT-3.6.0               | faction-mod-SNAPSHOT-3.6.0.jar                     | None                                     |
	| UC    | foamfix                           | 0.9.9.1-1.12.2               | foamfix-0.9.9.1-1.12.2-law.jar                     | None                                     |
	| UC    | icbmclassic                       | 1.12.2-3.1.0.38              | ICBM-classic-1.12.2-3.1.0b38.jar                   | None                                     |
	| UC    | inventorytweaks                   | 1.64-dev+release.110.b4fac73 | InventoryTweaks-1.64-dev.jar                       | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UC    | ironchest                         | 1.12.2-7.0.44.829            | ironchest-1.12.2-7.0.44.829.jar                    | None                                     |
	| UC    | itlt                              | 1.0.0                        | itlt-1.12-1.0.0.jar                                | None                                     |
	| UC    | journeymap                        | 1.12.2-5.5.2                 | journeymap-1.12.2-5.5.2.jar                        | None                                     |
	| UC    | malisiscore                       | 1.12.2-6.4.0                 | malisiscore-1.12.2-6.4.0.jar                       | None                                     |
	| UC    | malisisadvert                     | 1.12.2-6.1.0                 | malisisadvert-1.12.2-6.1.0.jar                     | None                                     |
	| UC    | mekanism                          | 1.12.2-9.4.13.349            | Mekanism-1.12.2-9.4.13.349.jar                     | None                                     |
	| UC    | mekanismgenerators                | 9.4.11                       | MekanismGenerators-1.12.2-9.4.13.349.jar           | None                                     |
	| UC    | mekanismtools                     | 9.4.11                       | MekanismTools-1.12.2-9.4.13.349.jar                | None                                     |
	| UC    | recipehandler                     | 0.10                         | NoMoreRecipeConflict-0.10(1.12.2).jar              | None                                     |
	| UC    | nuclearcraft                      | 2.10p                        | NuclearCraft-2.10p--1.12.2.jar                     | None                                     |
	| UC    | omlib                             | 3.0.0-148                    | omlib-1.12.2-3.0.0-148.jar                         | None                                     |
	| UC    | openmods                          | 0.11.5                       | OpenModsLib-1.12.2-0.11.5.jar                      | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UC    | openblocks                        | 1.7.6                        | OpenBlocks-1.12.2-1.7.6.jar                        | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UC    | openglider                        | @VERSION@                    | OpenGlider-1.12.1-1.1.0.jar                        | None                                     |
	| UC    | openmodularturrets                | 3.0.1-257                    | openmodularturrets-1.12.2-3.0.1-257.jar            | None                                     |
	| UC    | tesla                             | 1.0.63                       | Tesla-1.12.2-1.0.63.jar                            | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UC    | p455w0rdslib                      | 2.0.29                       | p455w0rdslib-1.12-2.0.29.jar                       | None                                     |
	| UC    | plustic                           | 6.5.2.0                      | plustic-6.5.2.0.jar                                | None                                     |
	| UC    | randomthings                      | 4.1.8                        | RandomThings-MC1.12.2-4.1.8.jar                    | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| UC    | reborncore                        | 3.9.0.315                    | RebornCore-1.12.2-3.9.0.315-universal.jar          | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| UC    | redstonearsenal                   | 2.5.1                        | RedstoneArsenal-1.12.2-2.5.1.13-universal.jar      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UC    | sgcraft                           | 1.13.2                       | SGCraft-1.2-mc1.12.2.jar                           | None                                     |
	| UC    | thermaldynamics                   | 2.5.1                        | ThermalDynamics-1.12.2-2.5.1.14-universal.jar      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UC    | simplyjetpacks                    | 2.2.7.45                     | SimplyJetpacks2-1.12.2-2.2.7.45.jar                | None                                     |
	| UC    | stevescarts                       | 2.4.21.105                   | StevesCarts-1.12.2-2.4.21.105.jar                  | None                                     |
	| UC    | wawla                             | 2.5.257                      | Wawla-1.12.2-2.5.257.jar                           | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UC    | wct                               | 3.9.67                       | WirelessCraftingTerminal-1.12.2-3.9.67.jar         | None                                     |
	| UC    | voxelsniper                       | 8.4.0                        | VoxelSniper-8.4.0.jar                              | None                                     |
	| UC    | mmcreboot                         | 2.2.2                        | MMCReboot-2.2.2-API-7.jar                          | None                                     |
	| UEE   | boop                              | 1.6.0                        | Boop-1.6.0.jar                                     | None                                     |
	| U     | worldedit                         | 6.1.9-SNAPSHOT               | worldedit-sponge-6.1.9-SNAPSHOT-dist.jar           | None                                     |
	| U     | clearmob                          | 1.12-2.0.1                   | ClearMob-1.12-2.0.1.jar                            | None                                     |
	| U     | pjc                               | 0.2.1                        | projectcore-7.0.0-0.2.1.jar                        | None                                     |
	| U     | itemchat                          | 1.2.1                        | ItemChat-1.2.1.jar                                 | None                                     |
	| U     | payrespects                       | 1.1.0                        | PayRespects-1.1.0.jar                              | None                                     |
	| U     | vigilate                          | 1.0.2                        | Vigilate-1.0.2.jar                                 | None                                     |
	| U     | nucleus                           | 1.3.7-S7.0                   | Nucleus-1.3.7-S7.0-MC1.12.2-plugin.jar             | None                                     |
	| U     | sleepvote                         | 1.1.0-S7.0                   | SleepVote-1.1.0-S7.0.jar                           | None                                     |
	| U     | spark                             | 1.0.3                        | spark.jar                                          | None                                     |
	| U     | pjp                               | 0.14.3                       | projectportals-7.1.0-0.14.3.jar                    | None                                     |
	| U     | luckperms                         | 4.1.7                        | LuckPerms-Sponge-4.1.7.jar                         | None                                     |
	| U     | craftbook                         | 4.0-Alpha1                   | craftbook-sponge-S7.1-4.0-Alpha1-dist.jar          | None                                     |
	| U     | holograms                         | 3.1                          | holograms-3.1.jar                                  | None                                     |
	| U     | pjw                               | 0.12.2                       | projectworlds-7.1.0-0.12.2.jar                     | None                                     |
	| U     | totaleconomy                      | 1.8.0                        | TotalEconomy-1.8.0.jar                             | None                                     |
	| U     | plan                              | 4.2.1                        | Plan.jar                                           | None                                     |
	| U     | aliases                           | 1.0                          | Aliases-1.0.jar                                    | None                                     |
	| U     | serverlistplus                    | 3.4.7                        | ServerListPlus-3.4.7-Universal.jar                 | None                                     |
	| U     | battlelog                         | 1.0.0                        | BattleLog.jar                                      | None                                     |
	| U     | webapi                            | 4.10.8-S7.1                  | webapi-4.10.8-S7.1.jar                             | None                                     |
	| U     | webapi-api                        | 4.10.8-S7.1                  | webapi-4.10.8-S7.1.jar                             | None                                     |
	| U     | friskstick                        | 1.0.1                        | FriskStick-v1.0.1.jar                              | None                                     |
	| U     | immersiveengineering              | 0.12-82                      | ImmersiveEngineering-0.12-82.jar                   | None                                     |

	Loaded coremods (and transformers): 
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.181.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
IELoadingPlugin (ImmersiveEngineering-0.12-82-core.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.31.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
LoadingPlugin (Quark-r1.4-125.jar)
  vazkii.quark.base.asm.ClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  invtweaks.forge.asm.ContainerTransformer
SpongeCoremod (spongeforge-1.12.2-2705-7.1.0-BETA-3151.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  openmods.core.OpenModsClassTransformer
LoadingPlugin (RandomThings-MC1.12.2-4.1.8.jar)
  lumien.randomthings.asm.ClassTransformer
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:ENABLED],[player_render_hook:ENABLED],[horse_null_fix:FINISHED]
	AE2 Version: stable rv5-stable-11 for Forge 14.23.1.2554
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by pie-flavor** [comment]
The crash report doesn't contain the real error. Please post the server log via gist.

**Comment by pie-flavor** [comment]
Closing due to lack of response.
